version: "3"

services:
    # https://hub.docker.com/_/mariadb
    mariadb:
        container_name: dc-mariadb
        env_file:
            - mariadb.env
        image: mariadb:latest
        networks:
            - nw-mariadb
        ports:
            - "3306:3306"
        restart: always
        tty: true
        volumes:
            - "./mariadb-data:/var/lib/mysql"
            - "./initdb.d:/docker-entrypoint-initdb.d/"

networks:
    nw-mariadb:
        driver: bridge
